// Stub header — the real file is generated by Xcode's "Generate Dependency Provider" build phase.
// This stub satisfies CocoaPods dependency resolution during `pod install`.
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>
#import <React/RCTComponentViewFactory.h>

NS_ASSUME_NONNULL_BEGIN

@interface RCTAppDependencyProvider : NSObject

@property (nonatomic, strong, readonly) NSArray<id<RCTBridgeModule>> *extraModulesForBridge;
@property (nonatomic, strong, readonly) RCTComponentViewFactory *componentViewFactory;

- (instancetype)init;

@end

NS_ASSUME_NONNULL_END
